    //bulk writes to firestore and populates 100 documents with fake data generated by faker.js
    //run only once 
    const fakeData = (event) => {
        event.preventDefault();
        var batch = firebase.firestore().batch();
        for (var count = 0; count <= 100; count++) {
            let money = (Math.random() * 1000).toFixed(1)+'0';
            var newEntry = firebase.firestore().collection('jobs').doc(count.toString());
            batch.set(newEntry, {'pickUp':faker.address.streetAddress()+' '+faker.address.city()+' '+
            faker.address.stateAbbr()+' '+faker.address.zipCodeByState('Queensland'), 'dropOff':faker.address.streetAddress()+' '+faker.address.city()+' '+
            faker.address.stateAbbr()+' '+faker.address.zipCodeByState('Queensland'), 'pay':money});
        }
        batch.commit().then(alert('success'));
    }

    //<button onClick={(event) => {fakeData(event)}}>populate jobs</button>