import React, {useState} from "react";
import '../index.css';
import firebase from 'firebase/app';
import faker from 'faker';

const config = {
    apiKey: "AIzaSyCXqvu1j3NQ4J303SKtBAcXZ_iFz5LhUdc",
    authDomain: "rapid-87eab.firebaseapp.com",
    databaseURL: "https://rapid-87eab.firebaseio.com",
    projectId: "rapid-87eab",
    storageBucket: "rapid-87eab.appspot.com",
    messagingSenderId: "724929581922",
    appId: "1:724929581922:web:5fa2ed8c80b8e52498d23b",
    measurementId: "G-SN0R0SLVTZ"
  }
  
if (!firebase.apps.length) {
    firebase.initializeApp(config);
}

faker.locale = 'en_AU';


const SignIn = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    
    //when the sign in button is clicked
    const signInHandler = (event, email, password) => {
        event.preventDefault();
        firebase.auth().signInWithEmailAndPassword(email, password).then(() => {
            window.location.href= '/jobs';
        })
        .catch((error) => {
            alert(error.message);
        });
    }

    const onChangeHandler = (event) => {
        const {name, value} = event.currentTarget;

        if (name==='userEmail') {
            setEmail(value);
        } else if (name === 'userPassword') {
            setPassword(value);
        }
    }

    //bulk writes to firestore and populates 100 documents with fake data generated by faker.js
    //run only once 
    const fakeData = (event) => {
        event.preventDefault();
        var batch = firebase.firestore().batch();
        for (var count = 0; count <= 100; count++) {
            let money = (Math.random() * 1000).toFixed(1)+'0';
            var newEntry = firebase.firestore().collection('jobs').doc(count.toString());
            batch.set(newEntry, {'pickUp':faker.address.streetAddress()+' '+faker.address.city()+' '+
            faker.address.stateAbbr()+' '+faker.address.zipCodeByState('Queensland'), 'dropOff':faker.address.streetAddress()+' '+faker.address.city()+' '+
            faker.address.stateAbbr()+' '+faker.address.zipCodeByState('Queensland'), 'pay':money});
        }
        batch.commit().then(alert('success'));
    }
    
    return (
        //logic for incorrect log in details not implemented
        <div className='signInbox'>
            <h1 className='title'>{'>'} Rapid Courier</h1>
            <div className='sign-in-border'>
                <form className='signInForm'>
                    <input type='email' className='input' 
                    name='userEmail' value={email} placeholder='Username'
                    id='userEmail'
                    onChange={(event) => onChangeHandler(event)} />

                    <input type='password' className='input' 
                    name='userPassword' value={password} placeholder='Password'
                    id='userPassword'
                    onChange={(event) => onChangeHandler(event)} />

                    <div className='sign-in-button-container'>
                        <button className='sign-in-button' 
                        onClick={(event) => {signInHandler(event, email, password)}}>
                            SIGN IN</button>
                    </div>

                </form>
            </div>
        </div>
    );
};
//<button className='sign-out-button'
//onClick={(event) => {firebase.auth().signOut().then(alert('signed out'))}}>SIGN OUT</button>
//<button onClick={(event) => {fakeData(event)}}>populate jobs</button> used for testing
export default SignIn;